version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"
      time: "06:00"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/backend"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]

  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
