version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/backend'
    schedule:
      interval: 'weekly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
      time: '06:00'
    commit-message:
      prefix: 'chore'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
    cooldown:
      default-days: 2
    groups:
      dependencies:
        patterns:
          - '*'
