set dotenv-load

default:
    @just --list

lint:
    golangci-lint run
    go mod verify

fmt:
    golangci-lint fmt

build:
    go build -v ./...

test:
    go test -v -race ./...

run-hub:
    go run ./cmd/hub

run-agent:
    go run ./cmd/agent