/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSystemInfoRouteImport } from './routes/_authenticated/admin/system-info'
import { Route as AuthenticatedAdminOidcProvidersRouteImport } from './routes/_authenticated/admin/oidc-providers'
import { Route as AuthenticatedApplicationsIdIndexRouteImport } from './routes/_authenticated/applications/$id.index'
import { Route as AuthenticatedApplicationsIdSettingsRouteImport } from './routes/_authenticated/applications/$id.settings'
import { Route as AuthenticatedApplicationsIdLogsRouteImport } from './routes/_authenticated/applications/$id.logs'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSystemInfoRoute =
  AuthenticatedAdminSystemInfoRouteImport.update({
    id: '/system-info',
    path: '/system-info',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOidcProvidersRoute =
  AuthenticatedAdminOidcProvidersRouteImport.update({
    id: '/oidc-providers',
    path: '/oidc-providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedApplicationsIdIndexRoute =
  AuthenticatedApplicationsIdIndexRouteImport.update({
    id: '/applications/$id/',
    path: '/applications/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdSettingsRoute =
  AuthenticatedApplicationsIdSettingsRouteImport.update({
    id: '/applications/$id/settings',
    path: '/applications/$id/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdLogsRoute =
  AuthenticatedApplicationsIdLogsRouteImport.update({
    id: '/applications/$id/logs',
    path: '/applications/$id/logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/applications/$id/logs': typeof AuthenticatedApplicationsIdLogsRoute
  '/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsRoute
  '/applications/$id/': typeof AuthenticatedApplicationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/applications/$id/logs': typeof AuthenticatedApplicationsIdLogsRoute
  '/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/_authenticated/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/applications/$id/logs': typeof AuthenticatedApplicationsIdLogsRoute
  '/_authenticated/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsRoute
  '/_authenticated/applications/$id/': typeof AuthenticatedApplicationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/oidc-providers'
    | '/admin/system-info'
    | '/admin/users'
    | '/admin/'
    | '/agents/'
    | '/applications/'
    | '/repositories/'
    | '/applications/$id/logs'
    | '/applications/$id/settings'
    | '/applications/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/oidc-providers'
    | '/admin/system-info'
    | '/admin/users'
    | '/admin'
    | '/agents'
    | '/applications'
    | '/repositories'
    | '/applications/$id/logs'
    | '/applications/$id/settings'
    | '/applications/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/'
    | '/_authenticated/admin/oidc-providers'
    | '/_authenticated/admin/system-info'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/agents/'
    | '/_authenticated/applications/'
    | '/_authenticated/repositories/'
    | '/_authenticated/applications/$id/logs'
    | '/_authenticated/applications/$id/settings'
    | '/_authenticated/applications/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system-info': {
      id: '/_authenticated/admin/system-info'
      path: '/system-info'
      fullPath: '/admin/system-info'
      preLoaderRoute: typeof AuthenticatedAdminSystemInfoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/oidc-providers': {
      id: '/_authenticated/admin/oidc-providers'
      path: '/oidc-providers'
      fullPath: '/admin/oidc-providers'
      preLoaderRoute: typeof AuthenticatedAdminOidcProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/applications/$id/': {
      id: '/_authenticated/applications/$id/'
      path: '/applications/$id'
      fullPath: '/applications/$id/'
      preLoaderRoute: typeof AuthenticatedApplicationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id/settings': {
      id: '/_authenticated/applications/$id/settings'
      path: '/applications/$id/settings'
      fullPath: '/applications/$id/settings'
      preLoaderRoute: typeof AuthenticatedApplicationsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id/logs': {
      id: '/_authenticated/applications/$id/logs'
      path: '/applications/$id/logs'
      fullPath: '/applications/$id/logs'
      preLoaderRoute: typeof AuthenticatedApplicationsIdLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminOidcProvidersRoute: typeof AuthenticatedAdminOidcProvidersRoute
  AuthenticatedAdminSystemInfoRoute: typeof AuthenticatedAdminSystemInfoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminOidcProvidersRoute: AuthenticatedAdminOidcProvidersRoute,
  AuthenticatedAdminSystemInfoRoute: AuthenticatedAdminSystemInfoRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedApplicationsIdLogsRoute: typeof AuthenticatedApplicationsIdLogsRoute
  AuthenticatedApplicationsIdSettingsRoute: typeof AuthenticatedApplicationsIdSettingsRoute
  AuthenticatedApplicationsIdIndexRoute: typeof AuthenticatedApplicationsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedApplicationsIdLogsRoute: AuthenticatedApplicationsIdLogsRoute,
  AuthenticatedApplicationsIdSettingsRoute:
    AuthenticatedApplicationsIdSettingsRoute,
  AuthenticatedApplicationsIdIndexRoute: AuthenticatedApplicationsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
