/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRepositoriesIndexRouteImport } from './routes/_authenticated/repositories/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications/index'
import { Route as AuthenticatedAgentsIndexRouteImport } from './routes/_authenticated/agents/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings/profile'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSystemInfoRouteImport } from './routes/_authenticated/admin/system-info'
import { Route as AuthenticatedAdminOidcProvidersRouteImport } from './routes/_authenticated/admin/oidc-providers'
import { Route as AuthenticatedAdminAuditLogRouteImport } from './routes/_authenticated/admin/audit-log'
import { Route as AuthenticatedApplicationsIdIndexRouteImport } from './routes/_authenticated/applications/$id/index'
import { Route as AuthenticatedApplicationsIdSettingsRouteImport } from './routes/_authenticated/applications/$id/settings'
import { Route as AuthenticatedApplicationsIdDetailsRouteImport } from './routes/_authenticated/applications/$id/details'
import { Route as AuthenticatedApplicationsIdSettingsIndexRouteImport } from './routes/_authenticated/applications/$id/settings/index'
import { Route as AuthenticatedApplicationsIdDetailsIndexRouteImport } from './routes/_authenticated/applications/$id/details/index'
import { Route as AuthenticatedApplicationsIdSettingsImagePollingRouteImport } from './routes/_authenticated/applications/$id/settings/image-polling'
import { Route as AuthenticatedApplicationsIdSettingsGeneralRouteImport } from './routes/_authenticated/applications/$id/settings/general'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedRepositoriesIndexRoute =
  AuthenticatedRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAgentsIndexRoute =
  AuthenticatedAgentsIndexRouteImport.update({
    id: '/agents/',
    path: '/agents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSystemInfoRoute =
  AuthenticatedAdminSystemInfoRouteImport.update({
    id: '/system-info',
    path: '/system-info',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOidcProvidersRoute =
  AuthenticatedAdminOidcProvidersRouteImport.update({
    id: '/oidc-providers',
    path: '/oidc-providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditLogRoute =
  AuthenticatedAdminAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedApplicationsIdIndexRoute =
  AuthenticatedApplicationsIdIndexRouteImport.update({
    id: '/applications/$id/',
    path: '/applications/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdSettingsRoute =
  AuthenticatedApplicationsIdSettingsRouteImport.update({
    id: '/applications/$id/settings',
    path: '/applications/$id/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdDetailsRoute =
  AuthenticatedApplicationsIdDetailsRouteImport.update({
    id: '/applications/$id/details',
    path: '/applications/$id/details',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedApplicationsIdSettingsIndexRoute =
  AuthenticatedApplicationsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsIdSettingsRoute,
  } as any)
const AuthenticatedApplicationsIdDetailsIndexRoute =
  AuthenticatedApplicationsIdDetailsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedApplicationsIdDetailsRoute,
  } as any)
const AuthenticatedApplicationsIdSettingsImagePollingRoute =
  AuthenticatedApplicationsIdSettingsImagePollingRouteImport.update({
    id: '/image-polling',
    path: '/image-polling',
    getParentRoute: () => AuthenticatedApplicationsIdSettingsRoute,
  } as any)
const AuthenticatedApplicationsIdSettingsGeneralRoute =
  AuthenticatedApplicationsIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedApplicationsIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/agents/': typeof AuthenticatedAgentsIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/applications/$id/details': typeof AuthenticatedApplicationsIdDetailsRouteWithChildren
  '/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsRouteWithChildren
  '/applications/$id/': typeof AuthenticatedApplicationsIdIndexRoute
  '/applications/$id/settings/general': typeof AuthenticatedApplicationsIdSettingsGeneralRoute
  '/applications/$id/settings/image-polling': typeof AuthenticatedApplicationsIdSettingsImagePollingRoute
  '/applications/$id/details/': typeof AuthenticatedApplicationsIdDetailsIndexRoute
  '/applications/$id/settings/': typeof AuthenticatedApplicationsIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/agents': typeof AuthenticatedAgentsIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/repositories': typeof AuthenticatedRepositoriesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/applications/$id': typeof AuthenticatedApplicationsIdIndexRoute
  '/applications/$id/settings/general': typeof AuthenticatedApplicationsIdSettingsGeneralRoute
  '/applications/$id/settings/image-polling': typeof AuthenticatedApplicationsIdSettingsImagePollingRoute
  '/applications/$id/details': typeof AuthenticatedApplicationsIdDetailsIndexRoute
  '/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/audit-log': typeof AuthenticatedAdminAuditLogRoute
  '/_authenticated/admin/oidc-providers': typeof AuthenticatedAdminOidcProvidersRoute
  '/_authenticated/admin/system-info': typeof AuthenticatedAdminSystemInfoRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/agents/': typeof AuthenticatedAgentsIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/repositories/': typeof AuthenticatedRepositoriesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/applications/$id/details': typeof AuthenticatedApplicationsIdDetailsRouteWithChildren
  '/_authenticated/applications/$id/settings': typeof AuthenticatedApplicationsIdSettingsRouteWithChildren
  '/_authenticated/applications/$id/': typeof AuthenticatedApplicationsIdIndexRoute
  '/_authenticated/applications/$id/settings/general': typeof AuthenticatedApplicationsIdSettingsGeneralRoute
  '/_authenticated/applications/$id/settings/image-polling': typeof AuthenticatedApplicationsIdSettingsImagePollingRoute
  '/_authenticated/applications/$id/details/': typeof AuthenticatedApplicationsIdDetailsIndexRoute
  '/_authenticated/applications/$id/settings/': typeof AuthenticatedApplicationsIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/settings'
    | '/admin/audit-log'
    | '/admin/oidc-providers'
    | '/admin/system-info'
    | '/admin/users'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/agents/'
    | '/applications/'
    | '/notifications/'
    | '/repositories/'
    | '/settings/'
    | '/applications/$id/details'
    | '/applications/$id/settings'
    | '/applications/$id/'
    | '/applications/$id/settings/general'
    | '/applications/$id/settings/image-polling'
    | '/applications/$id/details/'
    | '/applications/$id/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/admin/audit-log'
    | '/admin/oidc-providers'
    | '/admin/system-info'
    | '/admin/users'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/agents'
    | '/applications'
    | '/notifications'
    | '/repositories'
    | '/settings'
    | '/applications/$id'
    | '/applications/$id/settings/general'
    | '/applications/$id/settings/image-polling'
    | '/applications/$id/details'
    | '/applications/$id/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/admin/audit-log'
    | '/_authenticated/admin/oidc-providers'
    | '/_authenticated/admin/system-info'
    | '/_authenticated/admin/users'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/admin/'
    | '/_authenticated/agents/'
    | '/_authenticated/applications/'
    | '/_authenticated/notifications/'
    | '/_authenticated/repositories/'
    | '/_authenticated/settings/'
    | '/_authenticated/applications/$id/details'
    | '/_authenticated/applications/$id/settings'
    | '/_authenticated/applications/$id/'
    | '/_authenticated/applications/$id/settings/general'
    | '/_authenticated/applications/$id/settings/image-polling'
    | '/_authenticated/applications/$id/details/'
    | '/_authenticated/applications/$id/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/repositories/': {
      id: '/_authenticated/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof AuthenticatedRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents/': {
      id: '/_authenticated/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthenticatedAgentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system-info': {
      id: '/_authenticated/admin/system-info'
      path: '/system-info'
      fullPath: '/admin/system-info'
      preLoaderRoute: typeof AuthenticatedAdminSystemInfoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/oidc-providers': {
      id: '/_authenticated/admin/oidc-providers'
      path: '/oidc-providers'
      fullPath: '/admin/oidc-providers'
      preLoaderRoute: typeof AuthenticatedAdminOidcProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit-log': {
      id: '/_authenticated/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/applications/$id/': {
      id: '/_authenticated/applications/$id/'
      path: '/applications/$id'
      fullPath: '/applications/$id/'
      preLoaderRoute: typeof AuthenticatedApplicationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id/settings': {
      id: '/_authenticated/applications/$id/settings'
      path: '/applications/$id/settings'
      fullPath: '/applications/$id/settings'
      preLoaderRoute: typeof AuthenticatedApplicationsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id/details': {
      id: '/_authenticated/applications/$id/details'
      path: '/applications/$id/details'
      fullPath: '/applications/$id/details'
      preLoaderRoute: typeof AuthenticatedApplicationsIdDetailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications/$id/settings/': {
      id: '/_authenticated/applications/$id/settings/'
      path: '/'
      fullPath: '/applications/$id/settings/'
      preLoaderRoute: typeof AuthenticatedApplicationsIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsIdSettingsRoute
    }
    '/_authenticated/applications/$id/details/': {
      id: '/_authenticated/applications/$id/details/'
      path: '/'
      fullPath: '/applications/$id/details/'
      preLoaderRoute: typeof AuthenticatedApplicationsIdDetailsIndexRouteImport
      parentRoute: typeof AuthenticatedApplicationsIdDetailsRoute
    }
    '/_authenticated/applications/$id/settings/image-polling': {
      id: '/_authenticated/applications/$id/settings/image-polling'
      path: '/image-polling'
      fullPath: '/applications/$id/settings/image-polling'
      preLoaderRoute: typeof AuthenticatedApplicationsIdSettingsImagePollingRouteImport
      parentRoute: typeof AuthenticatedApplicationsIdSettingsRoute
    }
    '/_authenticated/applications/$id/settings/general': {
      id: '/_authenticated/applications/$id/settings/general'
      path: '/general'
      fullPath: '/applications/$id/settings/general'
      preLoaderRoute: typeof AuthenticatedApplicationsIdSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedApplicationsIdSettingsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditLogRoute: typeof AuthenticatedAdminAuditLogRoute
  AuthenticatedAdminOidcProvidersRoute: typeof AuthenticatedAdminOidcProvidersRoute
  AuthenticatedAdminSystemInfoRoute: typeof AuthenticatedAdminSystemInfoRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditLogRoute: AuthenticatedAdminAuditLogRoute,
  AuthenticatedAdminOidcProvidersRoute: AuthenticatedAdminOidcProvidersRoute,
  AuthenticatedAdminSystemInfoRoute: AuthenticatedAdminSystemInfoRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedApplicationsIdDetailsRouteChildren {
  AuthenticatedApplicationsIdDetailsIndexRoute: typeof AuthenticatedApplicationsIdDetailsIndexRoute
}

const AuthenticatedApplicationsIdDetailsRouteChildren: AuthenticatedApplicationsIdDetailsRouteChildren =
  {
    AuthenticatedApplicationsIdDetailsIndexRoute:
      AuthenticatedApplicationsIdDetailsIndexRoute,
  }

const AuthenticatedApplicationsIdDetailsRouteWithChildren =
  AuthenticatedApplicationsIdDetailsRoute._addFileChildren(
    AuthenticatedApplicationsIdDetailsRouteChildren,
  )

interface AuthenticatedApplicationsIdSettingsRouteChildren {
  AuthenticatedApplicationsIdSettingsGeneralRoute: typeof AuthenticatedApplicationsIdSettingsGeneralRoute
  AuthenticatedApplicationsIdSettingsImagePollingRoute: typeof AuthenticatedApplicationsIdSettingsImagePollingRoute
  AuthenticatedApplicationsIdSettingsIndexRoute: typeof AuthenticatedApplicationsIdSettingsIndexRoute
}

const AuthenticatedApplicationsIdSettingsRouteChildren: AuthenticatedApplicationsIdSettingsRouteChildren =
  {
    AuthenticatedApplicationsIdSettingsGeneralRoute:
      AuthenticatedApplicationsIdSettingsGeneralRoute,
    AuthenticatedApplicationsIdSettingsImagePollingRoute:
      AuthenticatedApplicationsIdSettingsImagePollingRoute,
    AuthenticatedApplicationsIdSettingsIndexRoute:
      AuthenticatedApplicationsIdSettingsIndexRoute,
  }

const AuthenticatedApplicationsIdSettingsRouteWithChildren =
  AuthenticatedApplicationsIdSettingsRoute._addFileChildren(
    AuthenticatedApplicationsIdSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAgentsIndexRoute: typeof AuthenticatedAgentsIndexRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedRepositoriesIndexRoute: typeof AuthenticatedRepositoriesIndexRoute
  AuthenticatedApplicationsIdDetailsRoute: typeof AuthenticatedApplicationsIdDetailsRouteWithChildren
  AuthenticatedApplicationsIdSettingsRoute: typeof AuthenticatedApplicationsIdSettingsRouteWithChildren
  AuthenticatedApplicationsIdIndexRoute: typeof AuthenticatedApplicationsIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAgentsIndexRoute: AuthenticatedAgentsIndexRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedRepositoriesIndexRoute: AuthenticatedRepositoriesIndexRoute,
  AuthenticatedApplicationsIdDetailsRoute:
    AuthenticatedApplicationsIdDetailsRouteWithChildren,
  AuthenticatedApplicationsIdSettingsRoute:
    AuthenticatedApplicationsIdSettingsRouteWithChildren,
  AuthenticatedApplicationsIdIndexRoute: AuthenticatedApplicationsIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
