// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthStatus int32

const (
	HealthStatus_HEALTH_STATUS_UNSPECIFIED HealthStatus = 0
	HealthStatus_HEALTH_STATUS_HEALTHY     HealthStatus = 1
	HealthStatus_HEALTH_STATUS_UNHEALTHY   HealthStatus = 2
)

// Enum value maps for HealthStatus.
var (
	HealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
	}
	HealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
	}
)

func (x HealthStatus) Enum() *HealthStatus {
	p := new(HealthStatus)
	*p = x
	return p
}

func (x HealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (HealthStatus) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x HealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthStatus.Descriptor instead.
func (HealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Pong
	//	*ClientMessage_KeyExchangeResponse
	//	*ClientMessage_EncryptedPayload
	//	*ClientMessage_DeployResult
	//	*ClientMessage_PullImagesResult
	//	*ClientMessage_DeleteResult
	//	*ClientMessage_ApplicationStatusReport
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetPong() *PongResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *ClientMessage) GetKeyExchangeResponse() *KeyExchangeResponse {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_KeyExchangeResponse); ok {
			return x.KeyExchangeResponse
		}
	}
	return nil
}

func (x *ClientMessage) GetEncryptedPayload() *EncryptedPayload {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_EncryptedPayload); ok {
			return x.EncryptedPayload
		}
	}
	return nil
}

func (x *ClientMessage) GetDeployResult() *DeployResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_DeployResult); ok {
			return x.DeployResult
		}
	}
	return nil
}

func (x *ClientMessage) GetPullImagesResult() *PullImagesResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_PullImagesResult); ok {
			return x.PullImagesResult
		}
	}
	return nil
}

func (x *ClientMessage) GetDeleteResult() *DeleteResult {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_DeleteResult); ok {
			return x.DeleteResult
		}
	}
	return nil
}

func (x *ClientMessage) GetApplicationStatusReport() *ApplicationStatusReport {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_ApplicationStatusReport); ok {
			return x.ApplicationStatusReport
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Pong struct {
	Pong *PongResponse `protobuf:"bytes,1,opt,name=pong,proto3,oneof"`
}

type ClientMessage_KeyExchangeResponse struct {
	KeyExchangeResponse *KeyExchangeResponse `protobuf:"bytes,2,opt,name=key_exchange_response,json=keyExchangeResponse,proto3,oneof"`
}

type ClientMessage_EncryptedPayload struct {
	EncryptedPayload *EncryptedPayload `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3,oneof"`
}

type ClientMessage_DeployResult struct {
	DeployResult *DeployResult `protobuf:"bytes,4,opt,name=deploy_result,json=deployResult,proto3,oneof"`
}

type ClientMessage_PullImagesResult struct {
	PullImagesResult *PullImagesResult `protobuf:"bytes,5,opt,name=pull_images_result,json=pullImagesResult,proto3,oneof"`
}

type ClientMessage_DeleteResult struct {
	DeleteResult *DeleteResult `protobuf:"bytes,6,opt,name=delete_result,json=deleteResult,proto3,oneof"`
}

type ClientMessage_ApplicationStatusReport struct {
	ApplicationStatusReport *ApplicationStatusReport `protobuf:"bytes,7,opt,name=application_status_report,json=applicationStatusReport,proto3,oneof"`
}

func (*ClientMessage_Pong) isClientMessage_Payload() {}

func (*ClientMessage_KeyExchangeResponse) isClientMessage_Payload() {}

func (*ClientMessage_EncryptedPayload) isClientMessage_Payload() {}

func (*ClientMessage_DeployResult) isClientMessage_Payload() {}

func (*ClientMessage_PullImagesResult) isClientMessage_Payload() {}

func (*ClientMessage_DeleteResult) isClientMessage_Payload() {}

func (*ClientMessage_ApplicationStatusReport) isClientMessage_Payload() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Ping
	//	*ServerMessage_KeyExchangeInit
	//	*ServerMessage_EncryptedPayload
	//	*ServerMessage_DeployRequest
	//	*ServerMessage_AgentSettings
	//	*ServerMessage_PullImagesRequest
	//	*ServerMessage_DeleteRequest
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetPing() *PingRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ServerMessage) GetKeyExchangeInit() *KeyExchangeInit {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_KeyExchangeInit); ok {
			return x.KeyExchangeInit
		}
	}
	return nil
}

func (x *ServerMessage) GetEncryptedPayload() *EncryptedPayload {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_EncryptedPayload); ok {
			return x.EncryptedPayload
		}
	}
	return nil
}

func (x *ServerMessage) GetDeployRequest() *DeployRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_DeployRequest); ok {
			return x.DeployRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetAgentSettings() *AgentSettings {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AgentSettings); ok {
			return x.AgentSettings
		}
	}
	return nil
}

func (x *ServerMessage) GetPullImagesRequest() *PullImagesRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_PullImagesRequest); ok {
			return x.PullImagesRequest
		}
	}
	return nil
}

func (x *ServerMessage) GetDeleteRequest() *DeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Ping struct {
	Ping *PingRequest `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type ServerMessage_KeyExchangeInit struct {
	KeyExchangeInit *KeyExchangeInit `protobuf:"bytes,2,opt,name=key_exchange_init,json=keyExchangeInit,proto3,oneof"`
}

type ServerMessage_EncryptedPayload struct {
	EncryptedPayload *EncryptedPayload `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload,proto3,oneof"`
}

type ServerMessage_DeployRequest struct {
	DeployRequest *DeployRequest `protobuf:"bytes,4,opt,name=deploy_request,json=deployRequest,proto3,oneof"`
}

type ServerMessage_AgentSettings struct {
	AgentSettings *AgentSettings `protobuf:"bytes,5,opt,name=agent_settings,json=agentSettings,proto3,oneof"`
}

type ServerMessage_PullImagesRequest struct {
	PullImagesRequest *PullImagesRequest `protobuf:"bytes,6,opt,name=pull_images_request,json=pullImagesRequest,proto3,oneof"`
}

type ServerMessage_DeleteRequest struct {
	DeleteRequest *DeleteRequest `protobuf:"bytes,7,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

func (*ServerMessage_Ping) isServerMessage_Payload() {}

func (*ServerMessage_KeyExchangeInit) isServerMessage_Payload() {}

func (*ServerMessage_EncryptedPayload) isServerMessage_Payload() {}

func (*ServerMessage_DeployRequest) isServerMessage_Payload() {}

func (*ServerMessage_AgentSettings) isServerMessage_Payload() {}

func (*ServerMessage_PullImagesRequest) isServerMessage_Payload() {}

func (*ServerMessage_DeleteRequest) isServerMessage_Payload() {}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type KeyExchangeInit struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MlkemEncapsulationKey []byte                 `protobuf:"bytes,1,opt,name=mlkem_encapsulation_key,json=mlkemEncapsulationKey,proto3" json:"mlkem_encapsulation_key,omitempty"`
	X25519PublicKey       []byte                 `protobuf:"bytes,2,opt,name=x25519_public_key,json=x25519PublicKey,proto3" json:"x25519_public_key,omitempty"`
	HubSignature          []byte                 `protobuf:"bytes,3,opt,name=hub_signature,json=hubSignature,proto3" json:"hub_signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *KeyExchangeInit) Reset() {
	*x = KeyExchangeInit{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeInit) ProtoMessage() {}

func (x *KeyExchangeInit) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeInit.ProtoReflect.Descriptor instead.
func (*KeyExchangeInit) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *KeyExchangeInit) GetMlkemEncapsulationKey() []byte {
	if x != nil {
		return x.MlkemEncapsulationKey
	}
	return nil
}

func (x *KeyExchangeInit) GetX25519PublicKey() []byte {
	if x != nil {
		return x.X25519PublicKey
	}
	return nil
}

func (x *KeyExchangeInit) GetHubSignature() []byte {
	if x != nil {
		return x.HubSignature
	}
	return nil
}

type KeyExchangeResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	MlkemCiphertext      []byte                 `protobuf:"bytes,1,opt,name=mlkem_ciphertext,json=mlkemCiphertext,proto3" json:"mlkem_ciphertext,omitempty"`
	AgentX25519PublicKey []byte                 `protobuf:"bytes,2,opt,name=agent_x25519_public_key,json=agentX25519PublicKey,proto3" json:"agent_x25519_public_key,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *KeyExchangeResponse) Reset() {
	*x = KeyExchangeResponse{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyExchangeResponse) ProtoMessage() {}

func (x *KeyExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyExchangeResponse.ProtoReflect.Descriptor instead.
func (*KeyExchangeResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *KeyExchangeResponse) GetMlkemCiphertext() []byte {
	if x != nil {
		return x.MlkemCiphertext
	}
	return nil
}

func (x *KeyExchangeResponse) GetAgentX25519PublicKey() []byte {
	if x != nil {
		return x.AgentX25519PublicKey
	}
	return nil
}

type EncryptedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedPayload) Reset() {
	*x = EncryptedPayload{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedPayload) ProtoMessage() {}

func (x *EncryptedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedPayload.ProtoReflect.Descriptor instead.
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *EncryptedPayload) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedPayload) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DeployRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicationName string                 `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	ComposeFile     string                 `protobuf:"bytes,4,opt,name=compose_file,json=composeFile,proto3" json:"compose_file,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployRequest) Reset() {
	*x = DeployRequest{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployRequest) ProtoMessage() {}

func (x *DeployRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployRequest.ProtoReflect.Descriptor instead.
func (*DeployRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeployRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeployRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeployRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

func (x *DeployRequest) GetComposeFile() string {
	if x != nil {
		return x.ComposeFile
	}
	return ""
}

type DeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicationName string                 `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeleteRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteResult) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeleteResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeployResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployResult) Reset() {
	*x = DeployResult{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployResult) ProtoMessage() {}

func (x *DeployResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployResult.ProtoReflect.Descriptor instead.
func (*DeployResult) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *DeployResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeployResult) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *DeployResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type AgentSettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ImagePollSettings []*ImagePollSettings   `protobuf:"bytes,1,rep,name=image_poll_settings,json=imagePollSettings,proto3" json:"image_poll_settings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AgentSettings) Reset() {
	*x = AgentSettings{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSettings) ProtoMessage() {}

func (x *AgentSettings) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSettings.ProtoReflect.Descriptor instead.
func (*AgentSettings) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *AgentSettings) GetImagePollSettings() []*ImagePollSettings {
	if x != nil {
		return x.ImagePollSettings
	}
	return nil
}

type ImagePollSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId   string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Enabled         bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IntervalSeconds int64                  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	DeleteOldImages bool                   `protobuf:"varint,4,opt,name=delete_old_images,json=deleteOldImages,proto3" json:"delete_old_images,omitempty"`
	ApplicationName string                 `protobuf:"bytes,5,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImagePollSettings) Reset() {
	*x = ImagePollSettings{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePollSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePollSettings) ProtoMessage() {}

func (x *ImagePollSettings) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePollSettings.ProtoReflect.Descriptor instead.
func (*ImagePollSettings) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ImagePollSettings) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ImagePollSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ImagePollSettings) GetIntervalSeconds() int64 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

func (x *ImagePollSettings) GetDeleteOldImages() bool {
	if x != nil {
		return x.DeleteOldImages
	}
	return false
}

func (x *ImagePollSettings) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

type PullImagesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId   string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	ApplicationName string                 `protobuf:"bytes,3,opt,name=application_name,json=applicationName,proto3" json:"application_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullImagesRequest) Reset() {
	*x = PullImagesRequest{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImagesRequest) ProtoMessage() {}

func (x *PullImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImagesRequest.ProtoReflect.Descriptor instead.
func (*PullImagesRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *PullImagesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PullImagesRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *PullImagesRequest) GetApplicationName() string {
	if x != nil {
		return x.ApplicationName
	}
	return ""
}

type PullImagesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ImagesUpdated bool                   `protobuf:"varint,4,opt,name=images_updated,json=imagesUpdated,proto3" json:"images_updated,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImagesResult) Reset() {
	*x = PullImagesResult{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImagesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImagesResult) ProtoMessage() {}

func (x *PullImagesResult) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImagesResult.ProtoReflect.Descriptor instead.
func (*PullImagesResult) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *PullImagesResult) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PullImagesResult) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *PullImagesResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PullImagesResult) GetImagesUpdated() bool {
	if x != nil {
		return x.ImagesUpdated
	}
	return false
}

func (x *PullImagesResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ApplicationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId string                 `protobuf:"bytes,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	Health        HealthStatus           `protobuf:"varint,2,opt,name=health,proto3,enum=messages.HealthStatus" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatus) Reset() {
	*x = ApplicationStatus{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatus) ProtoMessage() {}

func (x *ApplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatus.ProtoReflect.Descriptor instead.
func (*ApplicationStatus) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *ApplicationStatus) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *ApplicationStatus) GetHealth() HealthStatus {
	if x != nil {
		return x.Health
	}
	return HealthStatus_HEALTH_STATUS_UNSPECIFIED
}

// ApplicationStatusReport carries the health of every application managed by an
// agent in a single message, sent right after the agent connects.
type ApplicationStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*ApplicationStatus   `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatusReport) Reset() {
	*x = ApplicationStatusReport{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatusReport) ProtoMessage() {}

func (x *ApplicationStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatusReport.ProtoReflect.Descriptor instead.
func (*ApplicationStatusReport) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *ApplicationStatusReport) GetStatuses() []*ApplicationStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"\x93\x04\n" +
	"\rClientMessage\x12,\n" +
	"\x04pong\x18\x01 \x01(\v2\x16.messages.PongResponseH\x00R\x04pong\x12S\n" +
	"\x15key_exchange_response\x18\x02 \x01(\v2\x1d.messages.KeyExchangeResponseH\x00R\x13keyExchangeResponse\x12I\n" +
	"\x11encrypted_payload\x18\x03 \x01(\v2\x1a.messages.EncryptedPayloadH\x00R\x10encryptedPayload\x12=\n" +
	"\rdeploy_result\x18\x04 \x01(\v2\x16.messages.DeployResultH\x00R\fdeployResult\x12J\n" +
	"\x12pull_images_result\x18\x05 \x01(\v2\x1a.messages.PullImagesResultH\x00R\x10pullImagesResult\x12=\n" +
	"\rdelete_result\x18\x06 \x01(\v2\x16.messages.DeleteResultH\x00R\fdeleteResult\x12_\n" +
	"\x19application_status_report\x18\a \x01(\v2!.messages.ApplicationStatusReportH\x00R\x17applicationStatusReportB\t\n" +
	"\apayload\"\xf0\x03\n" +
	"\rServerMessage\x12+\n" +
	"\x04ping\x18\x01 \x01(\v2\x15.messages.PingRequestH\x00R\x04ping\x12G\n" +
	"\x11key_exchange_init\x18\x02 \x01(\v2\x19.messages.KeyExchangeInitH\x00R\x0fkeyExchangeInit\x12I\n" +
	"\x11encrypted_payload\x18\x03 \x01(\v2\x1a.messages.EncryptedPayloadH\x00R\x10encryptedPayload\x12@\n" +
	"\x0edeploy_request\x18\x04 \x01(\v2\x17.messages.DeployRequestH\x00R\rdeployRequest\x12@\n" +
	"\x0eagent_settings\x18\x05 \x01(\v2\x17.messages.AgentSettingsH\x00R\ragentSettings\x12M\n" +
	"\x13pull_images_request\x18\x06 \x01(\v2\x1b.messages.PullImagesRequestH\x00R\x11pullImagesRequest\x12@\n" +
	"\x0edelete_request\x18\a \x01(\v2\x17.messages.DeleteRequestH\x00R\rdeleteRequestB\t\n" +
	"\apayload\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\",\n" +
	"\fPongResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x9a\x01\n" +
	"\x0fKeyExchangeInit\x126\n" +
	"\x17mlkem_encapsulation_key\x18\x01 \x01(\fR\x15mlkemEncapsulationKey\x12*\n" +
	"\x11x25519_public_key\x18\x02 \x01(\fR\x0fx25519PublicKey\x12#\n" +
	"\rhub_signature\x18\x03 \x01(\fR\fhubSignature\"w\n" +
	"\x13KeyExchangeResponse\x12)\n" +
	"\x10mlkem_ciphertext\x18\x01 \x01(\fR\x0fmlkemCiphertext\x125\n" +
	"\x17agent_x25519_public_key\x18\x02 \x01(\fR\x14agentX25519PublicKey\"H\n" +
	"\x10EncryptedPayload\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\fR\n" +
	"ciphertext\"\xa3\x01\n" +
	"\rDeployRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12)\n" +
	"\x10application_name\x18\x03 \x01(\tR\x0fapplicationName\x12!\n" +
	"\fcompose_file\x18\x04 \x01(\tR\vcomposeFile\"\x80\x01\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12)\n" +
	"\x10application_name\x18\x03 \x01(\tR\x0fapplicationName\"\x93\x01\n" +
	"\fDeleteResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x93\x01\n" +
	"\fDeployResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\\\n" +
	"\rAgentSettings\x12K\n" +
	"\x13image_poll_settings\x18\x01 \x03(\v2\x1b.messages.ImagePollSettingsR\x11imagePollSettings\"\xd6\x01\n" +
	"\x11ImagePollSettings\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12)\n" +
	"\x10interval_seconds\x18\x03 \x01(\x03R\x0fintervalSeconds\x12*\n" +
	"\x11delete_old_images\x18\x04 \x01(\bR\x0fdeleteOldImages\x12)\n" +
	"\x10application_name\x18\x05 \x01(\tR\x0fapplicationName\"\x84\x01\n" +
	"\x11PullImagesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12)\n" +
	"\x10application_name\x18\x03 \x01(\tR\x0fapplicationName\"\xbe\x01\n" +
	"\x10PullImagesResult\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12%\n" +
	"\x0eimages_updated\x18\x04 \x01(\bR\rimagesUpdated\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"j\n" +
	"\x11ApplicationStatus\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\tR\rapplicationId\x12.\n" +
	"\x06health\x18\x02 \x01(\x0e2\x16.messages.HealthStatusR\x06health\"R\n" +
	"\x17ApplicationStatusReport\x127\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1b.messages.ApplicationStatusR\bstatuses*e\n" +
	"\fHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02B\fZ\n" +
	"./messagesb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_messages_proto_goTypes = []any{
	(HealthStatus)(0),               // 0: messages.HealthStatus
	(*ClientMessage)(nil),           // 1: messages.ClientMessage
	(*ServerMessage)(nil),           // 2: messages.ServerMessage
	(*PingRequest)(nil),             // 3: messages.PingRequest
	(*PongResponse)(nil),            // 4: messages.PongResponse
	(*KeyExchangeInit)(nil),         // 5: messages.KeyExchangeInit
	(*KeyExchangeResponse)(nil),     // 6: messages.KeyExchangeResponse
	(*EncryptedPayload)(nil),        // 7: messages.EncryptedPayload
	(*DeployRequest)(nil),           // 8: messages.DeployRequest
	(*DeleteRequest)(nil),           // 9: messages.DeleteRequest
	(*DeleteResult)(nil),            // 10: messages.DeleteResult
	(*DeployResult)(nil),            // 11: messages.DeployResult
	(*AgentSettings)(nil),           // 12: messages.AgentSettings
	(*ImagePollSettings)(nil),       // 13: messages.ImagePollSettings
	(*PullImagesRequest)(nil),       // 14: messages.PullImagesRequest
	(*PullImagesResult)(nil),        // 15: messages.PullImagesResult
	(*ApplicationStatus)(nil),       // 16: messages.ApplicationStatus
	(*ApplicationStatusReport)(nil), // 17: messages.ApplicationStatusReport
}
var file_messages_proto_depIdxs = []int32{
	4,  // 0: messages.ClientMessage.pong:type_name -> messages.PongResponse
	6,  // 1: messages.ClientMessage.key_exchange_response:type_name -> messages.KeyExchangeResponse
	7,  // 2: messages.ClientMessage.encrypted_payload:type_name -> messages.EncryptedPayload
	11, // 3: messages.ClientMessage.deploy_result:type_name -> messages.DeployResult
	15, // 4: messages.ClientMessage.pull_images_result:type_name -> messages.PullImagesResult
	10, // 5: messages.ClientMessage.delete_result:type_name -> messages.DeleteResult
	17, // 6: messages.ClientMessage.application_status_report:type_name -> messages.ApplicationStatusReport
	3,  // 7: messages.ServerMessage.ping:type_name -> messages.PingRequest
	5,  // 8: messages.ServerMessage.key_exchange_init:type_name -> messages.KeyExchangeInit
	7,  // 9: messages.ServerMessage.encrypted_payload:type_name -> messages.EncryptedPayload
	8,  // 10: messages.ServerMessage.deploy_request:type_name -> messages.DeployRequest
	12, // 11: messages.ServerMessage.agent_settings:type_name -> messages.AgentSettings
	14, // 12: messages.ServerMessage.pull_images_request:type_name -> messages.PullImagesRequest
	9,  // 13: messages.ServerMessage.delete_request:type_name -> messages.DeleteRequest
	13, // 14: messages.AgentSettings.image_poll_settings:type_name -> messages.ImagePollSettings
	0,  // 15: messages.ApplicationStatus.health:type_name -> messages.HealthStatus
	16, // 16: messages.ApplicationStatusReport.statuses:type_name -> messages.ApplicationStatus
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Pong)(nil),
		(*ClientMessage_KeyExchangeResponse)(nil),
		(*ClientMessage_EncryptedPayload)(nil),
		(*ClientMessage_DeployResult)(nil),
		(*ClientMessage_PullImagesResult)(nil),
		(*ClientMessage_DeleteResult)(nil),
		(*ClientMessage_ApplicationStatusReport)(nil),
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_Ping)(nil),
		(*ServerMessage_KeyExchangeInit)(nil),
		(*ServerMessage_EncryptedPayload)(nil),
		(*ServerMessage_DeployRequest)(nil),
		(*ServerMessage_AgentSettings)(nil),
		(*ServerMessage_PullImagesRequest)(nil),
		(*ServerMessage_DeleteRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
