package docker

import (
	"fmt"
	"os"
	"path/filepath"

	composetypes "github.com/compose-spec/compose-go/v2/types"
)

// Auto-loaded by a plain `docker compose up`, so manual runs keep the settings.
const overrideFileName = "compose.override.yaml"

const overrideFileHeader = "# Generated by OrcaCD on every deployment. Manual changes are overwritten.\n"

// orcaOverride mirrors applyOrcaLabels as an override for every service.
func orcaOverride(project *composetypes.Project, appID string) *composetypes.Project {
	override := &composetypes.Project{Services: make(composetypes.Services, len(project.Services))}
	for name := range project.Services {
		override.Services[name] = composetypes.ServiceConfig{Labels: orcaLabels(appID)}
	}
	return override
}

// writeComposeOverride is called on every deployment, since an override naming
// a removed service makes compose reject the project.
func writeComposeOverride(applicationDir string, override *composetypes.Project) error {
	content, err := override.MarshalYAML()
	if err != nil {
		return fmt.Errorf("render compose override: %w", err)
	}
	content = append([]byte(overrideFileHeader), content...)
	if err := os.WriteFile(filepath.Join(applicationDir, overrideFileName), content, 0o600); err != nil {
		return fmt.Errorf("write compose override: %w", err)
	}
	return nil
}
