name: CI

on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout code
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
        with:
          package_json_file: ./frontend/package.json

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "25.x.x"
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install dependencies
        working-directory: ./frontend
        run: pnpm i --frozen-lockfile

      - name: Run Linter
        working-directory: ./frontend
        run: node --run lint

      - name: Check Formatting
        working-directory: ./frontend
        run: node --run format:check

      - name: Build
        working-directory: ./frontend
        run: node --run build

      - name: Type Checking
        working-directory: ./frontend
        run: node --run typecheck

      - name: Check translations
        working-directory: ./frontend
        run: node --run translations:check

  backend:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: read
      id-token: write # For Codecov upload
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout code
        with:
          persist-credentials: false

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        name: Set up Go
        with:
          go-version: stable
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Install Buf CLI
        uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          setup_only: true
          version: 1.66.1

      - name: Verify Protobufs
        working-directory: ./backend
        run: |
          buf build --error-format=github-actions
          buf lint --error-format github-actions
          buf format --diff --error-format github-actions --exit-code

      - name: Compile Protobufs
        working-directory: ./backend
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.11
          buf generate

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11
          working-directory: ./backend

      - name: Verify dependencies
        working-directory: ./backend
        run: go mod verify

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Run Tests
        working-directory: ./backend
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          use_oidc: true
          fail_ci_if_error: true
