name: CI

on:
  push:

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: "24.x.x"

      - name: Setup Aikido Safe Chain
        working-directory: ./frontend
        run: |
          npm i -g @aikidosec/safe-chain
          safe-chain setup-ci

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci --safe-chain-skip-minimum-package-age

      - name: Run Linter
        working-directory: ./frontend
        run: node --run lint

      - name: Check Formatting
        working-directory: ./frontend
        run: node --run format:check

      - name: Type Checking
        working-directory: ./frontend
        run: node --run typecheck

      - name: Build
        working-directory: ./frontend
        run: node --run build

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        name: Checkout code

      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        name: Set up Go
        with:
          go-version: stable
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Install Protoc
        uses: arduino/setup-protoc@3ea1d70ac22caff0b66ed6cb37d5b7aadebd4623 # v3.0.0

      - name: Compile Protobufs
        working-directory: ./backend
        run: protoc --go_out=. --go_opt=paths=source_relative internal/proto/messages.proto

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11
          working-directory: ./backend

      - name: Verify dependencies
        working-directory: ./backend
        run: go mod verify

      - name: Build
        working-directory: ./backend
        run: go build -v ./...

      - name: Run Tests
        working-directory: ./backend
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          use_oidc: true
          fail_ci_if_error: true
